Update a Workflow-Record-Auto-Cleaner

diff --git a/.github/workflows/CMake.yml b/.github/workflows/CMake.yml
--- a/.github/workflows/CMake.yml
+++ b/.github/workflows/CMake.yml
@@ -18,66 +18,66 @@ jobs:
       contents: write
 
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@main
+      - name: Checkout Code
+        uses: actions/checkout@main
 
-    - name: Install NSIS
-      run: |
-        choco install nsis -y
-        echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+      - name: Install NSIS
+        run: |
+          choco install nsis -y
+          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
-    - name: Configure CMake of Release
-      if: github.event_name == 'release'
-      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
+      - name: Configure CMake of Release
+        if: github.event_name == 'release'
+        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
 
-    - name: Configure CMake of Test
-      if: github.event_name != 'release'
-      run: cmake -B build -DCMAKE_BUILD_TYPE=Test -G "MinGW Makefiles"
+      - name: Configure CMake of Test
+        if: github.event_name != 'release'
+        run: cmake -B build -DCMAKE_BUILD_TYPE=Test -G "MinGW Makefiles"
 
-    - name: Build
-      run: cmake --build build
+      - name: Build
+        run: cmake --build build
 
-    - name: Create an Setup Wizard
-      working-directory: build
-      run: make build
+      - name: Create an Setup Wizard
+        working-directory: build
+        run: make build
 
-    - name: Deploy
-      working-directory: build
-      run: |
-        $setup = Get-ChildItem -Filter "OpenVPNConfigManagerSetup-*.exe" | Select-Object -First 1
-        if (-not $setup)
-        {
-          Write-Error "Package not found."
-          exit 1
-        }
-        Start-Process -FilePath $setup.FullName -ArgumentList "/S" -Wait
-        echo "C:\Program Files (x86)\OpenVPN Config Manager" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+      - name: Deploy
+        working-directory: build
+        run: |
+          $setup = Get-ChildItem -Filter "OpenVPNConfigManagerSetup-*.exe" | Select-Object -First 1
+          if (-not $setup)
+          {
+            Write-Error "Package not found."
+            exit 1
+          }
+          Start-Process -FilePath $setup.FullName -ArgumentList "/S" -Wait
+          echo "C:\Program Files (x86)\OpenVPN Config Manager" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
-    - name: Test
-      working-directory: build
-      run: ctest --output-on-failure --verbose
+      - name: Test
+        working-directory: build
+        run: ctest --output-on-failure --verbose
 
-    - name: Create Attachments
-      working-directory: build
-      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
-      run : |
-        make zip
+      - name: Create Attachments
+        working-directory: build
+        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
+        run : |
+          make zip
 
-    - name: Upload Release Artifacts
-      uses: actions/upload-artifact@main
-      if: github.event_name == 'workflow_dispatch'
-      with:
-        name: OpenVPN-Config-Manager-Release
-        path: |
-          build/OpenVPNConfigManagerSetup-*.exe
-          build/OpenVPNConfigManagerSetup-*.zip
-        compression-level: 9
+      - name: Upload Release Artifacts
+        uses: actions/upload-artifact@main
+        if: github.event_name == 'workflow_dispatch'
+        with:
+          name: OpenVPN-Config-Manager-Release
+          path: |
+            build/OpenVPNConfigManagerSetup-*.exe
+            build/OpenVPNConfigManagerSetup-*.zip
+          compression-level: 9
 
-    - name: Upload to Release
-      uses: svenstaro/upload-release-action@master
-      if: github.event_name == 'release'
-      with:
-        file: build/*.{exe,zip}
-        overwrite: true
-        file_glob: true
-        draft: false
+      - name: Upload to Release
+        uses: svenstaro/upload-release-action@master
+        if: github.event_name == 'release'
+        with:
+          file: build/*.{exe,zip}
+          overwrite: true
+          file_glob: true
+          draft: false
