Add a setup wizard debug workflow and merge two jobs (#30)

diff --git a/.github/workflows/CMake.yml b/.github/workflows/CMake.yml
--- a/.github/workflows/CMake.yml
+++ b/.github/workflows/CMake.yml
@@ -9,26 +9,8 @@ on:
   workflow_dispatch:
 
 jobs:
-  debug:
-    runs-on: windows-latest
-
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v7.0.1
-
-    - name: Configure CMake
-      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles"
-
-    - name: Build
-      run: cmake --build build
-
-    - name: Test
-      working-directory: build
-      run: ctest
-
   build:
     runs-on: windows-latest
-    if: github.event_name == 'release'
 
     steps:
     - name: Checkout code
@@ -43,17 +25,36 @@ jobs:
     - name: Verify NSIS
       run: makensis -VERSION
 
-    - name: Configure CMake
+    - name: Configure CMake of Build
+      if: github.event_name == 'release'
       run: cmake -B build -DCMAKE_BUILD_TYPE=Build -G "MinGW Makefiles"
+
+    - name: Configure CMake of Debug
+      if: github.event_name != 'release'
+      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles"
 
     - name: Build
       run: cmake --build build
 
-    - name: Create an installation package
+    - name: Create an Setup Wizard
       run: make -C build build
+      
+    - name: Test Setup Wizard
+      working-directory: build
+      run: |
+        $setup = Get-ChildItem -Filter "OpenVPNConfigManagerSetup-*.exe" | Select-Object -First 1
+        if (-not $setup)
+        {
+          Write-Error "Package not found."
+          exit 1
+        }
+        Start-Process -FilePath $setup.FullName -ArgumentList "/S" -Wait
 
-    - name: List build directory
-      run: dir build
+    - name: Test
+      working-directory: build
+      run: |
+        echo "C:\Program Files (x86)\OpenVPN Config Manager" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+        ctest -C Debug --output-on-failure --verbose
 
     - name: Upload Release Artifacts
       uses: actions/upload-artifact@v4
@@ -63,6 +64,7 @@ jobs:
 
     - name: Upload to Release
       uses: svenstaro/upload-release-action@v2
+      if: github.event_name == 'release'
       with:
         file: build/*.exe
         overwrite: true
